### ISSUE TITLE
Initial raw spec

### ISSUE THREAD

**Issue by oskarth** [privacy-scaling-explorations/zkvm-ideas#2]
## Problem

We want a spec that explains the approach and various nitty gritty details so we have more confidence in the idea and can communicate it with others.

## Acceptance criteria

Raw spec published somewhere public (like this repo) that touches main areas and answers biggest questions.

**Comment by CPerezz** [comment]
Currently finishing the linear approach.

Next thing is to focus on the diagrams and explanation of Parallel Nova using both folds!

**Comment by oskarth** [comment]
Done https://zkresear.ch/t/towards-a-nova-based-zk-vm/105
