### ISSUE TITLE
Initial benchmarks for Nova vs other systems

### ISSUE THREAD

**Issue by oskarth** [privacy-scaling-explorations/zkvm-ideas#3]
## Problem

We want to have confidence that a Nova-based ZK-VM would be significantly better than existing Halo2 based VMs.

This is also useful for wider ecosystem to warrant more investment into Nova and similar proof systems in certain conditions.

While we primarily care about prover time, memory/ptau constraints are also relevant, especially for big circuits. We are especially interested in what parallelism unlocks.

## Notes

There are also other benchmark efforts in the wider ecosystem that makes sense to hook into. E.g.:

- https://github.com/celer-network/zk-benchmark
- https://github.com/zkCollective/zk-Harness

Currently we are basing structure based on Celer network.

We can run both on laptops as well as a powerful server. While running on a distributed network would be desirable, this involves more setup and would likely be a natural next step after initial benchmarks are done.

Also see [README](https://github.com/oskarth/recursive-hashing-bench/blob/main/README.md) for more details on current thinking and observations.

## Acceptance criteria

Benchmarks for Nova against Circom (naive) and Halo2 that shows different prover time per depth.

Ideally find a benchmark that shows where Nova has a x10 performance improvement.

**Comment by oskarth** [comment]
Running Nova native benchmarks https://github.com/microsoft/Nova/blob/main/benches/compressed-snark.rs#L33 to check only one step circuit, no recursion.

Constraints vs prover time:

```
10k 0.4s
100k 1.1s
1m 7s
10m 105s
```

We don't run out of memory so in Nova Scotia likely due to witness generation. CPUs maxed out so GPU/CUDA would be useful.

![Uploading 圖片.png…]()


This is random constraints so not comparable with SHA256, unless looking at order of magnitude of constraints.

**Comment by oskarth** [comment]
Bitcoin benchmarks https://hackmd.io/0gVClQ9IQiSXHYAK0Up9hg?view=

**Comment by oskarth** [comment]
Above numbers was actually CompressedSNARK which seems wrong.

RecursiveSNARK Nova native (https://github.com/microsoft/Nova/blob/main/benches/recursive-snark.rs#L79):

10k 90ms
100k 148ms
1m 650ms
10m ...

Parallel Nova native - maybe something wrong in it, seemed a bit off (https://github.com/privacy-scaling-explorations/Nova/pull/9):

10k 300ms
100k 400ms
1m 1.3s
10m 11.3s

cc @aleph-v 

---

Both run with this diff (to get x10 orders of magnitude)

```
-  let num_cons_verifier_circuit_primary = 9819;
+  let num_cons_verifier_circuit_primary = 10000;
   // we vary the number of constraints in the step circuit
   for &num_cons_in_augmented_circuit in
-    [9819, 16384, 32768, 65536, 131072, 262144, 524288, 1048576].iter()
+    [10000, 20000, 110000, 1010000, 10010000, 100010000].iter()
```

**Comment by oskarth** [comment]
Summary of benchmarks and conclusions https://hackmd.io/0gVClQ9IQiSXHYAK0Up9hg?both=

**Comment by aleph-v** [comment]
The Parallel Nova is a bit disappointing but not that surprising, it does three times as many folds per step. So you can see that the overhead goes from 3.3x to around 1.9 as the extra folding becomes the overhead. Either that or the memory bug makes this slower. I think best way to lower this overhead is to optimize the F' in parallel for the foldings used.

**Comment by oskarth** [comment]
I'll close this issue as we've done initial benchmarking above, especially in context of ZK Residency. There's still room for additional benchmarks, see "future benchmarks" in hackmd above.
